import type { Metadata } from 'next';
import { Footer, Header } from '@/components';

import 'swiper/css';
import 'swiper/css/navigation';
import '../styles/globals.css';

export const metadata: Metadata = {
    title: {
        default: 'پرشین',
        template: 'پرشین | %s',
    },
    description: 'Generated by Persian',
};

type RootLayoutProps = {
    children: React.ReactNode;
};

export default function RootLayout(props: Readonly<RootLayoutProps>) {
    const { children } = props;

    return (
        <html lang="en">
            <body className="antialiased min-h-screen w-screen flex flex-col bg-white-200">
                <Header />

                <main className="w-full flex-[2] pt-10 lg:pt-20">
                    {children}
                </main>

                <Footer />
            </body>
        </html>
    );
}
